### ISSUE TITLE
[Issue]:  World Gen Error  Trying to access unbound value

### ISSUE THREAD

**Issue by Kampftoast** [The-Nexus-Project/Limitless-7#117]
### What happened?

When trying to generate a world the game will crash. 
I tried it two times, both time with the same result.

### Pack Version

Version: 1.6.0

### To Reproduce

1. freshly install this pack in version 1.6.0
2. start the game
3. create new world (survival, allow cheats on)
4. game crashes during creation

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [x] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [x] No.

### Relevant log output / crash report.

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-05-16 16:05:50
Description: Exception in server tick loop

java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/structure / structory:taiga_ruin_surface]' from registry net.minecraft.core.MappedRegistry$1@23a7bc2
	at net.minecraft.core.Holder$Reference.m_203334_(Holder.java:147) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:holder_serialize,re:computing_frames,pl:accesstransformer:B,xf:fml:libx:holder_serialize,re:classloading,pl:accesstransformer:B,xf:fml:libx:holder_serialize}
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.m_255018_(ChunkGeneratorStructureState.java:75) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:APP:betterjungletemples.mixins.json:accessor.ChunkGeneratorStructureStateAccessor,pl:mixin:A}
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?] {}
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.m_255180_(ChunkGeneratorStructureState.java:79) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:APP:betterjungletemples.mixins.json:accessor.ChunkGeneratorStructureStateAccessor,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.m_254876_(ChunkGeneratorStructureState.java:66) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:APP:betterjungletemples.mixins.json:accessor.ChunkGeneratorStructureStateAccessor,pl:mixin:A}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?] {}
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.minecraft.world.level.chunk.ChunkGeneratorStructureState.m_255081_(ChunkGeneratorStructureState.java:67) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:APP:betterjungletemples.mixins.json:accessor.ChunkGeneratorStructureStateAccessor,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_255169_(ChunkGenerator.java:108) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:redirector.mixins.json:net.minecraft.world.level.chunk.ChunkGeneratorMixin,pl:mixin:APP:betterfortresses.mixins.json:DisableVanillaFortressesMixin,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchSpeedupMixin,pl:mixin:APP:structureessentials.mixins.json:StructureSearchTimeoutMixin,pl:mixin:APP:bettermineshafts.mixins.json:DisableVanillaMineshaftsMixin,pl:mixin:APP:idas.mixins.json:iceandfire.DisableIaFStructures,pl:mixin:APP:betterwitchhuts.mixins.json:DisableVanillaWitchHutsMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betterstrongholds.mixins.json:DisableVanillaStrongholdsMixin,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.server.level.ChunkMap.<init>(ChunkMap.java:162) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.<init>(ServerChunkCache.java:77) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.<init>(ServerLevel.java:209) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:the_bumblezone-common.mixins.json:world.ServerWorldMixin,pl:mixin:APP:immersive_weathering-common.mixins.json:ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:APP:observable.common.json:ServerLevelMixin,pl:mixin:APP:bedbenefits.mixins.json:MixinServerLevel,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:idas.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerLevelAccessor,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:337) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:308) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:63) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:APP:lithostitched.mixins.json:client.IntegratedServerMixin,pl:mixin:APP:blueprint.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231520!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}



[shortend because of max. char limit]
```

### Anything else to add?

I am using Prism Launcher

**Comment by Gbergz** [comment]
your install is most likely invalid, try using another launcher.

**Comment by Kampftoast** [comment]
Thanks for your reply.

Indeed, when using curseforge it does work.Thanks

**Comment by Gbergz** [comment]
Sweet, np!
