### ISSUE TITLE
[Issue]: If using the mod Extra Compat, the game will fail to load or create single player worlds

### ISSUE THREAD

**Issue by useracct1** [The-Nexus-Project/Limitless-7#120]
### What happened?

When using the mod Extra Compat, the game will fail to load or create single player worlds, showing the error "Failed to connect: Invalid player data", then kicking you to the server select screen. This is (presumably) because this error is coming from the game's internal server. The game does not close.

### Pack Version

Version: 1.9.0, also happened on 1.8.0

### To Reproduce

1. Add the mod Extra Compat to the modpack.
2. Launch the game.
3. Try to join or create a single player world.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		34: net.minecraftforge.eventbus.EventBus$$Lambda$1855/0x00000008008f7420@480052da
		35: LOW
		36: net.minecraftforge.eventbus.EventBus$$Lambda$1855/0x00000008008f7420@22c14812
net.minecraftforge.fml.ModLoadingException: Extra Compat (extra_compat) encountered an error during the done event phase
§7java.lang.NullPointerException: Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.2.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.17/net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.17/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227)
	at LAYER PLUGIN/fmlcore@1.20.1-47.2.17/net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326)
	at TRANSFORMER/forge@47.2.17/net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1633)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710)
	at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:48)
	at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.RecipeSorter.sendOrderToClient(RecipeSorter.java:84)
	at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.forge.SawmillForge.dataSync(SawmillForge.java:37)
	at TRANSFORMER/sawmill@1.20-1.3.15/net.mehvahdjukaar.sawmill.forge.__SawmillForge_dataSync_OnDatapackSyncEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null
	at TRANSFORMER/extra_compat@1.5.1/net.cyber_rat.extra_compat.ExtraCompat.addCreative(ExtraCompat.java:29)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at LAYER PLUGIN/javafmllanguage@1.20.1-47.2.17/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114)
	... 38 more

[17:59:22] [Server thread/ERROR]: Couldn't place player in world
net.minecraftforge.fml.ModLoadingException: Extra Compat (extra_compat) encountered an error during the done event phase
§7java.lang.NullPointerException: Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.20.1-47.2.17.jar%231556!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.17.jar%231555!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.17.jar%231555!/:?]
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.17.jar%231555!/:?]
	at net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1633) ~[forge-1.20.1-47.2.17-universal.jar%231559!/:?]
	at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.mehvahdjukaar.sawmill.RecipeSorter.refreshIfNeeded(RecipeSorter.java:48) ~[sawmill-1.20-1.3.15.jar%231406!/:?]
	at net.mehvahdjukaar.sawmill.RecipeSorter.sendOrderToClient(RecipeSorter.java:84) ~[sawmill-1.20-1.3.15.jar%231406!/:?]
	at net.mehvahdjukaar.sawmill.forge.SawmillForge.dataSync(SawmillForge.java:37) ~[sawmill-1.20-1.3.15.jar%231406!/:?]
	at net.mehvahdjukaar.sawmill.forge.__SawmillForge_dataSync_OnDatapackSyncEvent.invoke(.dynamic) ~[sawmill-1.20-1.3.15.jar%231406!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231554!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.cyber_rat.extra_compat.core.CompatCore.addCreative(net.minecraftforge.event.BuildCreativeModeTabContentsEvent)" because "compatCore" is null
	at net.cyber_rat.extra_compat.ExtraCompat.addCreative(ExtraCompat.java:29) ~[extra_compat-1.5.1.jar%231100!/:1.5.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2375!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.17.jar%231556!/:?]
	... 38 more
[17:59:22] [Server thread/INFO]: MCJAxolotl7 lost connection: Invalid player data
[17:59:22] [Server thread/INFO]: MCJAxolotl7 left the game
[17:59:22] [Server thread/INFO]: remove player wand
[17:59:22] [Server thread/WARN]: on player disconnect: player 'MCJAxolotl7' has no team?
[17:59:22] [Server thread/INFO]: Failed to load default records at /home/will/Documents/curseforge/minecraft/Instances/TNP Limitless 7 - LL7/config/jecalculation/records.json.
[17:59:22] [Server thread/INFO]: Stopping singleplayer server as player logged out
[17:59:22] [Server thread/INFO]: Shutdown Complete
[17:59:22] [Server thread/INFO]: Stopping server
[17:59:22] [Server thread/INFO]: Saving players
[17:59:22] [Server thread/INFO]: Saving worlds
```

### Anything else to add?

I stopped the log when it started logging the player out, as that happened the same as if you quit the world, it gracefully quit and saved properly. Given that I play with ~730 mods, I backup worlds and no data was lost. My computer specs: Linux Mint 21.2 Cinnamon, Nvidia 3080 Ti, Intel i9-12900kf, 32GB DDR5-4400 RAM (18000 MBs allocated), Dell Alienware Aurora R13 motherboard (dell does not use commodity parts, it's dell custom/proprietary), 1TB Kioxia M.2 SSD, CurseForge for Linux v. 1.251.0.17831. I tried installing XL Packets (the accepted fix for this error in the origins-fabric github issues thread), no help from that.

**Comment by Gbergz** [comment]
Report this to Extra Compat, this mod is not in the pack by default.

**Comment by useracct1** [comment]
found somebody else with this issue! this is with the new version of the mod!
