### ISSUE TITLE
Server crash when player enters The End

### ISSUE THREAD

**Issue by Orion-Cluster** [The-Nexus-Project/Limitless-7#2]
### What happened?

We had two players on our server and one entered the End, the server crashed.  I restarted the server and joined (in the overworld) and had no issues.  As soon as the other players (in the End) joins the server crashes.  

### Pack Version

Version: TNP Limitless 7 0.9.0

### To Reproduce

1.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-07-17 22:13:14
Description: Exception ticking world

java.lang.NullPointerException: Cannot read field "f_20378_" because "p_19977_" is null
	at net.minecraft.world.entity.Entity.m_6380_(Entity.java:2783) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.getEyeHeightAccess(Entity.java:3456) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeEntity.getEyeHeightForge(IForgeEntity.java:442) ~[forge-1.20.1-47.1.12-universal.jar%23902!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.12-universal.jar%23902!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.boss.EnderDragonPart.<init>(EnderDragonPart.java:20) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:endertrigon.mixins.json:MixinEnderDragonPart,pl:mixin:A}
	at net.minecraft.world.entity.boss.enderdragon.EnderDragon.<init>(EnderDragon.java:92) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endertrigon.mixins.json:MixinEnderDragon,pl:mixin:APP:endertrigon.mixins.json:IMixinEnderDragon,pl:mixin:A}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64110_(EndDragonFight.java:403) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64103_(EndDragonFight.java:211) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64095_(EndDragonFight.java:157) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:319) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.entity.Entity.m_6380_(Entity.java:2783) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraft.world.entity.Entity.getEyeHeightAccess(Entity.java:3456) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeEntity.getEyeHeightForge(IForgeEntity.java:442) ~[forge-1.20.1-47.1.12-universal.jar%23902!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:262) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:usefulslimeCommon.mixins.json:EntityMixin,pl:mixin:APP:mixins.irons_spellbooks.json:EntityMixin,pl:mixin:APP:balm.mixins.json:EntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:earthmobsmod.mixins.json:EntityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.suffocation.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:collections.fluid_submersion.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:relics.mixins.json:MixinEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:A}
	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.12-universal.jar%23902!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.boss.EnderDragonPart.<init>(EnderDragonPart.java:20) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:endertrigon.mixins.json:MixinEnderDragonPart,pl:mixin:A}
	at net.minecraft.world.entity.boss.enderdragon.EnderDragon.<init>(EnderDragon.java:92) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:endertrigon.mixins.json:MixinEnderDragon,pl:mixin:APP:endertrigon.mixins.json:IMixinEnderDragon,pl:mixin:A}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,xf:fml:forge:forge_method_redirector,re:classloading,xf:fml:forge:forge_method_redirector,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType,pl:mixin:A}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64110_(EndDragonFight.java:403) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64103_(EndDragonFight.java:211) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.dimension.end.EndDragonFight.m_64095_(EndDragonFight.java:157) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:319) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:neruina-common.mixins.json:ServerWorldMixin,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['HeyImBri'/1409, l='ServerLevel[world]', x=100.50, y=49.00, z=0.50]]
	Chunk stats: 1878
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (164,63,223), Section: (at 4,15,15 in 10,3,13; chunk contains blocks 160,0,208 to 175,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8845936 game time, 2970439 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 15820 (now: false), thunder time: 114308 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23897!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:bcc.mixins.json:MinecraftServerMixinn,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
```

**Comment by Gbergz** [comment]
Update to 0.10.0 and make sure Forge is 47.1.3 when updated.
