### ISSUE TITLE
[Issue]: Crash on opening quests

### ISSUE THREAD

**Issue by RebelGhosts** [The-Nexus-Project/Limitless-7#24]
### What happened?

When clicking on the getting wood quest came crashes

### Pack Version

Version: 0.24.0

### To Reproduce

1.open minecraft quest line and click getting wood

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

### Relevant log output / crash report.

```shell
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.20.1-47.1.3-universal.jar%231297!/:?] {re:mixin,re:classloading}
	at at.nuxnux.skinnedlanterns.CreativeTab.lambda$static$0(CreativeTab.java:27) ~[skinned_lanterns-1.20.1-1.3.5.jar%231194!/:1.3.5] {re:classloading}
	at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:589) ~[?:?] {}
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?] {}
	at at.nuxnux.skinnedlanterns.CreativeTab.lambda$static$1(CreativeTab.java:25) ~[skinned_lanterns-1.20.1-1.3.5.jar%231194!/:1.3.5] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onCreativeModeTabBuildContents(ForgeHooksClient.java:1206) ~[forge-1.20.1-47.1.3-universal.jar%231297!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[client-1.20.1-20230612.114412-srg.jar%231292!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:CreativeModeTabMixin,pl:mixin:APP:mixins.ipnext.json:MixinItemGroup,pl:mixin:A}
	at net.minecraft.world.item.CreativeModeTabs.m_268957_(CreativeModeTabs.java:1696) ~[client-1.20.1-20230612.114412-srg.jar%231292!/:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.item.CreativeModeTabs.m_269421_(CreativeModeTabs.java:1695) ~[client-1.20.1-20230612.114412-srg.jar%231292!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.m_269226_(CreativeModeTabs.java:1710) ~[client-1.20.1-20230612.114412-srg.jar%231292!/:?] {re:classloading,pl:accesstransformer:B}
	at dev.latvian.mods.itemfilters.DisplayStacksCache.lambda$computeMatchingStacks$0(DisplayStacksCache.java:41) ~[item-filters-forge-2001.1.0-build.55.jar%231006!/:2001.1.0-build.55] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at dev.latvian.mods.itemfilters.DisplayStacksCache.computeMatchingStacks(DisplayStacksCache.java:41) ~[item-filters-forge-2001.1.0-build.55.jar%231006!/:2001.1.0-build.55] {re:classloading}
	at dev.latvian.mods.itemfilters.DisplayStacksCache.getCachedDisplayStacks(DisplayStacksCache.java:28) ~[item-filters-forge-2001.1.0-build.55.jar%231006!/:2001.1.0-build.55] {re:classloading}
	at dev.latvian.mods.itemfilters.api.IItemFilter.getDisplayItemStacks(IItemFilter.java:44) ~[item-filters-forge-2001.1.0-build.55.jar%231006!/:2001.1.0-build.55] {re:classloading}
	at dev.latvian.mods.itemfilters.api.ItemFiltersAPI.getDisplayItemStacks(ItemFiltersAPI.java:93) ~[item-filters-forge-2001.1.0-build.55.jar%231006!/:2001.1.0-build.55] {re:classloading}
	at dev.ftb.mods.ftbquests.quest.task.ItemTask.getValidDisplayItems(ItemTask.java:153) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:mixin,re:classloading,pl:mixin:APP:ftbqoptimizer.mixins.json:ItemTaskMixin,pl:mixin:A}
	at dev.ftb.mods.ftbquests.quest.task.ItemTask.getAltIcon(ItemTask.java:172) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:mixin,re:classloading,pl:mixin:APP:ftbqoptimizer.mixins.json:ItemTaskMixin,pl:mixin:A}
	at dev.ftb.mods.ftbquests.quest.QuestObjectBase.getIcon(QuestObjectBase.java:300) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:classloading,re:mixin}
	at dev.ftb.mods.ftbquests.quest.task.Task.drawGUI(Task.java:201) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:classloading,re:mixin}
	at dev.ftb.mods.ftbquests.client.gui.quests.TaskButton.drawIcon(TaskButton.java:161) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:classloading}
	at dev.ftb.mods.ftbquests.client.gui.quests.TaskButton.draw(TaskButton.java:169) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.drawWidget(Panel.java:232) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.draw(Panel.java:209) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.drawWidget(Panel.java:232) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.draw(Panel.java:209) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.drawWidget(Panel.java:232) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.draw(Panel.java:209) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftbquests.client.gui.quests.ViewQuestPanel.draw(ViewQuestPanel.java:767) ~[ftb-quests-forge-2001.1.4.jar%23956!/:2001.1.4] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.drawWidget(Panel.java:232) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.Panel.draw(Panel.java:209) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.BaseScreen.draw(BaseScreen.java:236) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at dev.ftb.mods.ftblibrary.ui.ScreenWrapper.m_88315_(ScreenWrapper.java:116) ~[ftb-library-forge-2001.1.3.jar%23955!/:2001.1.3] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%231292!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ScreenMixin,pl:mixin:APP:cumulus_menus.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:emi.mixins.json:ScreenMixin,pl:mixin:APP:konkrete.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.general.mixin.json:IMixinScreen,pl:mixin:APP:fancymenu.general.mixin.json:MixinScreen,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:APP:mixins.transmog.common.json:ScreenMixin,pl:mixin:APP:aether.mixins.json:client.accessor.ScreenAccessor,pl:mixin:APP:controlling.mixins.json:AccessScreen,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorScreen,pl:mixin:APP:screenshot_viewer.mixins.json:ScreenMixin,pl:mixin:APP:ae2.mixins.json:WrappedGenericStackTooltipModIdMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.3-universal.jar%231297!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.3-universal.jar%231297!/:?] {re:mixin,re:classloading,pl:mixin:A}
```

**Comment by thatbirdliam** [comment]
I still have this issue in 0.27.0, same quest too
