### ISSUE TITLE
[Issue]: Power cables from multiple mods not connecting to Powah reactors

### ISSUE THREAD

**Issue by BossRedRanger** [The-Nexus-Project/Limitless-7#65]
### What happened?

Once updating to 0.50.0, no power was coming into my Flux power network. Flux plugs, Mekanism universal cables, nor even Powah mod power cables will connect to the Powah mod reactors. Placing universal cables sometimes cause server crashes.

### Pack Version

Version: 0.50.0

### To Reproduce

1. power cables placed in power output portion of reactor doesn't connect.
2. Tried with Mekanism universal cables, Powah mod cables, & Flux Networks power plug

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [ ] Using Oculus
- [X] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by theArhar** [comment]
mekanism cable connects only to front port

**Comment by theArhar** [comment]
if you connect hw wire connector from immersive engineering you can get
`[14:35:37] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class owmii.powah.forge.ForgeEnvHandler$8 cannot be cast to class net.minecraftforge.energy.IEnergyStorage (owmii.powah.forge.ForgeEnvHandler$8 is in module powah@5.0.4 of loader 'TRANSFORMER' @39c93af6; net.minecraftforge.energy.IEnergyStorage is in module forge@47.2.17 of loader 'TRANSFORMER' @39c93af6)
	at blusunrize.immersiveengineering.common.blocks.metal.EnergyConnectorBlockEntity.tickServer(EnergyConnectorBlockEntity.java:126) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%231083!/:?]
	at blusunrize.immersiveengineering.common.blocks.ticking.IEServerTickableBE.lambda$makeTicker$0(IEServerTickableBE.java:23) ~[ImmersiveEngineering-1.20.1-10.0.0-169.jar%231083!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.world.level.Level.redirect$dnp000$redirectTick(Level.java:4540) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%231416!/:?]
	... 5 more`
