### ISSUE TITLE
[Issue]: Game crash/ neruina  caught ticking entity due to backpack/quiver keybind conflict

### ISSUE THREAD

**Issue by deanobdg** [The-Nexus-Project/Limitless-7#9]
### What happened?

Pressing B with both 'Nyf's Quiver' diamond quiver in a bauble slot and a 'sophisticated backpack' backpack (I used a diamond backpack) in your bauble slot, the error will be caught in neruina and close the server on a multiplayer server and will freeze until you relaunch in singleplayer.
![Capture](https://github.com/The-Nexus-Project/Limitless-7/assets/7017893/42249bc1-f811-4f6e-8cd7-d3bcb275f14b)

### Pack Version

Version: 0.20.1

### To Reproduce

1. Wear a diamond quiver from 'Nyf's quiver' mod in a bauble slot.

2. Wear a sophisticated backpack mod, diamond backpack. (The upgraded version may be irrelevant but this is what I was using.)

3. Press B then escape to close the menus then press B again in a somewhat quick succession.

### Are you using OptiFine or Oculus?

- [ ] Using OptiFine
- [X] Using Oculus
- [ ] No. None of them. Unmodified.

### Are you on a Server?

- [X] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
net.minecraft.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?] {}
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150407_(AbstractContainerMenu.java:218) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:AbstractContainerMenuAccessor,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:mixins.ae2things.json:CursedInternalSlotMixin,pl:mixin:APP:relics.mixins.json:MixinAbstractContainerMenu,pl:mixin:A}
        at net.minecraft.world.inventory.AbstractContainerMenu.m_38946_(AbstractContainerMenu.java:171) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:AbstractContainerMenuAccessor,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:mixins.ae2things.json:CursedInternalSlotMixin,pl:mixin:APP:relics.mixins.json:MixinAbstractContainerMenu,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayer.m_8119_(ServerPlayer.java:435) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:uteamcore.mixins.json:common.ServerPlayerMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:APP:securitycraft.mixins.json:camera.ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23917!/:2.0.0-build.9999] {re:mixin,re:classloading}
        at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:25) ~[NoSeeNoTick-2.0.0-1.20.1.jar%23917!/:2.0.0-build.9999] {re:mixin,re:classloading}
        at net.minecraft.world.level.Level.m_46653_(Level.java:2541) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:computing_frames,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:noseenotick.mixins.json:EntityTickMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:blockswap.mixins.json:MixinLevel,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:crafttweaker.mixins.json:common.transform.world.level.MixinServerLevel,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldAccessor,pl:mixin:APP:friendsandfoes-common.mixins.json:ServerWorldMixin,pl:mixin:APP:leavesbegone.common.mixins.json:ServerLevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.entity_class_groups.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%231075!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
```

### Anything else to add?

A temporary resolution to the issue was to change the key binds for 'Nyf's quiver' to another key so both menus would not be opened at the same time causing the crash.

Not sure if the crash report above is helpful or not but this is copied/pasted from my friend's dedicated server for version 0.20.1.

**Comment by Kirbmyster** [comment]
Got a similar issue involving specifically Sophisticated Backpacks and piglin brutes as well, could be same thing?
Crashes servers and freezes single player until reboot.
